# Generated by Django 5.0.6 on 2024-06-02 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_scoring_favorites', '0002_scoring'),
        ('products', '0014_alter_brand_image_name_alter_product_image_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درج')),
                ('favorite_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_user1', to=settings.AUTH_USER_MODEL, verbose_name='کاربر علاقه مند')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_product', to='products.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'علاقه',
                'verbose_name_plural': 'علایق',
            },
        ),
    ]
